### ISSUE TITLE
How To Config for Angular Conventional Commits

### ISSUE THREAD

**Issue by matthew-valenti** [SystangoTechnologies/commit-message-lint#1]
Thanks for making this tool available! How do I configure commit lint for Angular Conventional Commits?

https://github.com/angular/angular/blob/22b96b9/CONTRIBUTING.md#-commit-message-guidelines

On the GitHub marketplace commit lint displays the following: "Commit Lint allows you to add a layer of control over the title of your pull request and commit, forcing to respect the formatting convention that you choose (Angular, Atom, Ember ...)"

However, in the documentation it states we need to define two regex statements: PR_TITLE_REGEX and COMMIT_MESSAGE_REGEX.

I can't find any information on the regex used for Angular Conventional Commits. I'm not even sure if it can be expressed as a regex statement.

We currently use https://github.com/conventional-changelog/commitlint in our CI and are looking for something similar for a GitHub pull request.

**Comment by sumits-systango** [comment]
Hi @matthew-valenti 
Thanks for your interest in the app. But I am not sure where did you read the description. This description does not correspond to this app. Following is the app link for your reference:

[Commit Message Lint](https://github.com/marketplace/commit-message-lint)

This app only allows you to define a regex for commit messages and PR title and then validate based on those. Following wiki link provides an example:

[https://github.com/SystangoTechnologies/commit-message-validator/wiki/Commit-Message-Validator](https://github.com/SystangoTechnologies/commit-message-validator/wiki/Commit-Message-Validator)

Do let us know if you have further queries.
