### ISSUE TITLE
Waiting for status to be reported

### ISSUE THREAD

**Issue by pdunhamp44** [SystangoTechnologies/commit-message-lint#11]
Status check is not finishing, instead I get this message:
<img width="757" alt="Screen Shot 2020-02-24 at 1 50 57 PM" src="https://user-images.githubusercontent.com/46973219/75186081-dc91fb00-570c-11ea-83e5-670ce8d9e8ca.png">

**Comment by sumits-systango** [comment]
Let us check @pdunhamp44

**Comment by sumits-systango** [comment]
Are you facing the issue with new requests as well? It could be related to github performance issue as well.

**Comment by pdunhamp44** [comment]
I've had to turn it off for one of our repos since this keeps happening, as recently as today.

**Comment by stephen-opal** [comment]
I'm experiencing this as well

**Comment by stephen-opal** [comment]
Never mind, there was a parsing error with my regex in my `config.yml`. Sorry for the spam!

**Comment by sumits-systango** [comment]
@pdunhamp44 can you let us know if your repo is public or private? And is it a person repo or is it withing an organisation?
The app has some restrictions in private repo inside an organisation but otherwise it is working fine.

**Comment by sumits-systango** [comment]
@pdunhamp44 
The app works with private repos as well with the latest update. It should be working fine if you try again.

**Comment by pallav-systango** [comment]
Closing Issue
