### ISSUE TITLE
Read access to code permission

### ISSUE THREAD

**Issue by IgorAnohin** [SystangoTechnologies/commit-message-lint#13]
Hi guys!
Your app looks awesome.

I wanted to install it to my private repos, but it requests "Read code" permission.
![image](https://user-images.githubusercontent.com/31206535/78841713-c2835200-7a06-11ea-8d5c-155f58398e6a.png)

On your Wiki page, I read that _"The new permission is required to support private repos **without accessing the code**."_

This is the first github app, that I tried to install. Could someone describe me, why it requesting "Read code" permission? 
Thanks in advance

**Comment by sumits-systango** [comment]
We added this permission to work with private repos under an organisation. The documentation is updated now.

**Comment by sumits-systango** [comment]
@IgorAnohin 
We have removed the code access permission after latest updated. This is published now. Documentation is also updated.
