### ISSUE TITLE
Check stucks on expected state

### ISSUE THREAD

**Issue by pasali** [SystangoTechnologies/commit-message-lint#18]
Hi,
We are using this app on our private repositories. It was working like expected untill today. On the all repositories checks stuck at expected state.

**Comment by ajaij** [comment]
Happening for me as well, the check is not event getting triggered, after 12 hrs its still showing. I tried disabling and re-enable the branch settings, suspend the app even after these attempts am getting the below msg for both old and new PR's.
 
`Commit Message Lint Expected — Waiting for status to be reported `

Note: Mine is a private org repo

**Comment by sumits-systango** [comment]
Private repos should not be a problem anymore. We are taking a look into this.

**Comment by pasali** [comment]
@sumits-systango did you have any chance to look at this ?

**Comment by sumits-systango** [comment]
The issue is with our cloud provider. This should be fixed today.

**Comment by pdunhamp44** [comment]
this is still an issue for us

**Comment by pasali** [comment]
It is working now for us.

**Comment by ajaij** [comment]
@sumits-systango this issue has re-surfaced again, can you please look into this ?
