### ISSUE TITLE
Lint is not working

### ISSUE THREAD

**Issue by cemo** [SystangoTechnologies/commit-message-lint#21]
Hi, 

Can someone take a look on app please? It is not working. App is not responding.

![image](https://user-images.githubusercontent.com/44156/95241038-ebe63480-0815-11eb-9a45-db36a26f1574.png)

**Comment by sumits-systango** [comment]
We'll check this @cemo

**Comment by sumits-systango** [comment]
This is resolved now @cemo

**Comment by cemo** [comment]
@sumits-systango we have again same problem.

**Comment by apresswala-systango** [comment]
Should be working now @cemo  Please check
