### ISSUE TITLE
Says failed but didnt

### ISSUE THREAD

**Issue by SamuelJohnsonMedia** [SystangoTechnologies/commit-message-lint#22]
Great tool, thanks for this; however minor issue in that the linter said it both failed and succeeded:

![Linter](https://user-images.githubusercontent.com/68481262/95625799-01a36600-0a71-11eb-9f21-8cc3590a6986.png)

and clicking details:

![Linter2](https://user-images.githubusercontent.com/68481262/95626242-d79e7380-0a71-11eb-852b-66ba9fe58d5f.png)

**Comment by apresswala-systango** [comment]
Hey @SamuelJohnsonMedia 
Thanks for the feedback. We have resolved the issue. It should work fine now.

**Comment by Alessthana** [comment]
@apresswala-systango  How can I configure this commit-message-lint on only one branch, As I only need this setup on the develop branch and not on qa.

**Comment by apresswala-systango** [comment]
@Alessthana  Right now it doesn't have the option to restrict to some branches. It would run for all the branches.
