### ISSUE TITLE
Can't enable the app, as its not showing up in status check section.

### ISSUE THREAD

**Issue by ajaij** [SystangoTechnologies/commit-message-lint#23]
Under the "Status checks found in the last week for this repository ", option, I am not able to see the app name.
I have added the config.yml in the code and its been more than 2 days, yet the option is not showing up.

**Comment by ajaij** [comment]
@sumits-systango can you help me out to resolve my issue ?

**Comment by apresswala-systango** [comment]
Hi @ajaij  
Can you confirm if the app is installed in your repo ?
because if app is installed and all the configurations are set then when you create a PR it will show in checks section.
Can you try creating a new PR and then check ?

Alternatively, please try removing the app and re-installing that.

**Comment by ajaij** [comment]
Hi @apresswala-systango , yes the app is installed. I have created many PR's and yet its not showing up in the Branch Rule section. I event tried suspending & re-installing getting the same response.

**Note:** I have added the config.yml file in my repos as well.


<img width="791" alt="Screenshot 2020-10-22 at 12 11 09 PM" src="https://user-images.githubusercontent.com/45552514/96834661-ffbda780-145f-11eb-960d-3d63403cac1d.png">


<img width="472" alt="Screenshot 2020-10-22 at 12 12 30 PM" src="https://user-images.githubusercontent.com/45552514/96834675-0815e280-1460-11eb-9bfe-bbad6bf34a30.png">

**Comment by apresswala-systango** [comment]
Hi @ajaij  
Can you tell me where you have put your config.yml file ?
The config.yml file should be in the .github folder (and .github should be at the root of the repo)

If you have already placed that in the .github folder and still not working then can you tell me the name of your repo ?
We will check the specific issue with your repo and help you to resolve that.

**Comment by ajaij** [comment]
Hello @apresswala-systango , yes as you have mentioned the file is placed under .github folder. Its a private repo of our organization, let me know if we can connect via call to resolve the issue. Thanks

**Comment by apresswala-systango** [comment]
A call would not be feasible for us for next few days @ajaij . Could you provide us just the name of your repository so that our team can quickly check the logs from our side and help you with that ?

**Comment by ajaij** [comment]
sure @apresswala-systango, the repo names are `revvsales/reactgrid` & ` revvsales/revv-auth `

**Comment by ajaij** [comment]
any update on this @apresswala-systango  ?

**Comment by apresswala-systango** [comment]
Hi @ajaij 
By checking the logs for both of the repositories, it appears that you haven't provided the configuration for `COMMIT_MESSAGE_REGEX` in config.yml file.
The key is either missing or empty.

Please check the Configuration Instructions for more info.

**Comment by ajaij** [comment]
@apresswala-systango I need to check regex only for the PR Title, hence I added like this, is other configs are also mandatory? This is how my config file looks like.

<img width="1253" alt="Screenshot 2020-11-05 at 12 48 01 PM" src="https://user-images.githubusercontent.com/45552514/98209556-26520700-1f65-11eb-82b1-4466c2b0872f.png">

**Comment by apresswala-systango** [comment]
@ajaij  The main purpose of this app is to check for commit-messages, so that's a mandatory config to be provided.
What you can do is you can pass such a regex in COMMIT_MESSAGE_REGEX which will satisfy any message in the commit.
for example:
COMMIT_MESSAGE_REGEX: /.*/

**Comment by Kal-Elx** [comment]
Hi! Was this solved?

I'm having the same problem. I installed the app previously today and made two pull requests but the checks aren't made.
@apresswala-systango would you mind checking the logs for my repository?

Here is the repository: https://github.com/dibbs-team/dibbs

**Comment by apresswala-systango** [comment]
Hi @Kal-Elx 
We have checked the logs of your repository and found that the problem is with the regex you have in the config.yml file for COMMIT_MESSAGE_REGEX. You have a blank space in your regex pattern after (\([a-z ]+\))?:  and that is causing the yml to break when we receive it in the request.
We are working on a solution for this but in the meantime you can use \s for the blank space in the regex as a possible solution.
Please try this out and let us know if that doesn't work.

**Comment by Kal-Elx** [comment]
It seems to work now! Thanks @apresswala-systango
