### ISSUE TITLE
Check hangs and never reports

### ISSUE THREAD

**Issue by wesleyhartp44** [SystangoTechnologies/commit-message-lint#25]
We have this enabled on many of our private repositories, and it has started hanging again recently, blocking all of our merges. It never reports a status or any info at all. Just says "Waiting for status to be reported". This is a recurrence of the following issues:
https://github.com/SystangoTechnologies/commit-message-lint/issues/11
https://github.com/SystangoTechnologies/commit-message-lint/issues/18

**Comment by apresswala-systango** [comment]
@wesleyhartp44  The issue has been resolved. Please check on your end and let us know if the problem persists.

**Comment by ajaij** [comment]
@apresswala-systango  for me it started 2 days back, this issue is still persisting in my repos.

**Comment by apresswala-systango** [comment]
@ajaij  This has been an intermittent issue. We have fixed this and are working to plug any remaining holes. You should be able to use the app now.

**Comment by wesleyhartp44** [comment]
Yes, this issue is happening again for us today

**Comment by apresswala-systango** [comment]
@ajaij  @wesleyhartp44 Let us know if you are still facing the issue. 
Feel free to close this if everything is working well.

**Comment by wesleyhartp44** [comment]
Just had it again this morning

**Comment by apresswala-systango** [comment]
@wesleyhartp44  Can you send us your repository URL ? We will check from our end and get back to you.

**Comment by wesleyhartp44** [comment]
It has been working since yesterday. Will let you know if it happens again. Thank you
