### ISSUE TITLE
Checks not running

### ISSUE THREAD

**Issue by KaiserKarel** [SystangoTechnologies/commit-message-lint#26]
Checks are not running at all, most likely due to some error on my part.

My .github/config.yml:

```
PR_TITLE_REGEX: "^#\d* - .*"
COMMIT_MESSAGE_REGEX: "(build|ci|chore|docs|feat|fix|perf|refactor|revert|style|test)\(.*\): .*"
```

**Comment by apresswala-systango** [comment]
Hi @KaiserKarel, The regex you are providing is incorrect that's why the checks are not running.
Please try with the below regex and let us know if you are still facing any issue.
You might need to alter the regex as per your exact need but the format remains the same.

```
PR_TITLE_REGEX: /^#\d* - .*/
COMMIT_MESSAGE_REGEX: /(build|ci|chore|docs|feat|fix|perf|refactor|revert|style|test)(\(.*\))?:(.*)*/
```
