### ISSUE TITLE
Status not updated to success or failed it shows always "waiting for status to be reported"

### ISSUE THREAD

**Issue by nibro7778** [SystangoTechnologies/commit-message-lint#4]
Hi Team,

I have installed an application and updated config.yml file with regex value. application check working properly on single commit but as soon as I updated with the second commit I don't know why I am not able to see any checks under check tab. Also, commit Message Lint status always shows me '`ommit Message Lint Expected — Waiting for status to be reported`'

can anyone help me out with this issue 

Regards,
Niraj

**Comment by sumits-systango** [comment]
@nibro7778 
Thanks for the feedback. Can you provide some screenshots of what you are seeing? Also, can you tell me whether you added a new commit to same PR or generated a new PR?

**Comment by nibro7778** [comment]
Hi @sumits-systango,

yes, I have added the commit under the same PR which I have created earlier. Please find below screenshot. still, the status shows me  `Waiting for status to be reported` 

![Capture](https://user-images.githubusercontent.com/16951150/62840771-3b4cd580-bce3-11e9-947e-2d86846e84c7.PNG)
 
Do let me know if you need more information

**Comment by sumits-systango** [comment]
Let us take a look into it.

**Comment by sumits-systango** [comment]
@nibro7778 
This is fixed. The fix won't work on existing PRs, you will need to create a new PR. Or push a new commit in existing PR, the app will check all the commits.

**Comment by Alessthana** [comment]
I'm facing a similar issue, I checks tab I'm getting this message "Waiting for checks information..." and nothing happens from then. I've tried raising a new PR, But still no success. Can someone help with this? It worked fine till 2 days back, But It's not working since yesterday. Not sure what got changed and I'm pretty sure, No config change has been done.Thanks.

**Comment by apresswala-systango** [comment]
Should be working now @Alessthana. Please check

**Comment by Alessthana** [comment]
@apresswala-systango  How can I configure this for specific branch? I only want this check to happen on my development branch and not on other branches. Thanks.

**Comment by apresswala-systango** [comment]
@Alessthana  Right now it doesn't have the option to restrict to some branches. It would run for all the branches.

**Comment by sumits-systango** [comment]
@Alessthana 
We have added the feature request in our pipeline. We'll notify the feature is released.
