### ISSUE TITLE
Message validation failed!!!

### ISSUE THREAD

**Issue by nibro7778** [SystangoTechnologies/commit-message-lint#5]
I have requested [this issue](https://github.com/SystangoTechnologies/commit-message-lint/issues/4) to be fixed. After fixing this I was trying to test it with a new pull request but seems like it's not working. My commit and pull request title is according to whatever regex I have provided in the config file but still, the application gives me the following validation message.

```
Pull request title is invalid
Commit messages are invalid
sha: 335fe0e | message: feat: ABC-123- test commit for commit lint app 
```

Please have look to this [PR ](https://github.com/nibro7778/mydiary/pull/11/checks?check_run_id=198763744) for more details

**Comment by sumits-systango** [comment]
@nibro7778 
We'll take a look and get back to you.

**Comment by sumits-systango** [comment]
@nibro7778 
You need to add an extra backslash in the regex. Try this one:
(?<verbs>(fix:|feat:|docs:|style:|refactor:|test:|chore:)\\s)(?<message>)
