### ISSUE TITLE
App not showing up in 'checks' section

### ISSUE THREAD

**Issue by coleHafner** [SystangoTechnologies/commit-message-lint#7]
Hi. Thanks for this great app. It's just the solution I was looking for.

I have attempted to set it up on our private repo within our organization (according to #2 , this should work). However, I can't get it to show up in the checks summary section. And when I go to the checks section, I see the app show up, but I just get a blank page. (see attached)

![Screen Shot 2019-08-27 at 4 48 17 PM](https://user-images.githubusercontent.com/380835/63815718-858ca400-c8ea-11e9-88ef-ccfcda88adf7.png)

Here is my `.github/config.yml` file:

```
PR_TITLE_REGEX: /(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\([a-z0-9\s]+\))?(:\s)([a-z0-9\s]+)/i
COMMIT_MESSAGE_REGEX: /.+/i
```

I'm new to GitHub apps. How can I troubleshoot this?

**Comment by sumits-systango** [comment]
@coleHafner 
This could be an issue with private repo within an organisation. We are checking this and will get back to you.

**Comment by sumits-systango** [comment]
Hi @coleHafner 
This issue is specific to private repo inside an organisation. And I've not been able to arrange one for testing. I'll try for one and update you soon.

**Comment by xxBedy** [comment]
Same problem. It works on my private repo 13 days ago. But stops working. I tried to configure it on different private repository, reinstall application without success.

**Comment by sumits-systango** [comment]
We have made a few changes to the way we pickup the configuration. The location of config file is same. Give it a go once.

**Comment by sumits-systango** [comment]
We have made some changes to the way we pick up configuration. Have a go once again.

**Comment by cjhay4** [comment]
I've been trying out this tool for the first time today, both with a private repo and a public one (after changing the original test-repo to be public), and in either case I'm met with the following when I go to the 'Checks' tab:

![image](https://user-images.githubusercontent.com/18172543/67905156-16c00700-fb36-11e9-8703-5877d0578fb5.png)

**Comment by malikwaleedtariq** [comment]
Running in to same problem with private repo

**Comment by sumits-systango** [comment]
@cjhay4 
this issue is resolved, you should be able to view the result with public repos. We are still working on the private repo issue.

**Comment by Alessthana** [comment]
Is it working with private repos inside an organization? I find success in my personal private repo but not with org private repo. Can someone help? @sumits-systango
