### ISSUE TITLE
It would be great to have a custom message on failure

### ISSUE THREAD

**Issue by j0tt** [SystangoTechnologies/commit-message-lint#8]
Team loves this, but I get dms because it just says "validation failed". it would be nice to output the expected format.

**Comment by sumits-systango** [comment]
Hey @j0tt 
Thanks for the interest. Are you looking for a way to customise and configure the validation output message? What kind of messages formats are you thinking of?

**Comment by j0tt** [comment]
For us it would be nice to have a customs output so we could say something like:  “try something like [user story|task|bug] 34635: I did a good thing to this code”

We’re trying to not be too prescriptive with format and just make sure there’s an issue number and the issue type are in the message.

**Comment by MSFT-Chris-Barrett** [comment]
+1 to having a custom message with an example of a valid format.  Just being told "your PR title is wrong" leaves me at "okay, I need to change the PR title... does it need beachball emoji added to become valid?"  For a silly, exagerrated example of how the open-ended message doesn't help lead a user to making a successful commit/PR request.

**Comment by sumits-systango** [comment]
This is done as part of release 2.2.0.
